name: Main->Prod Automatic PR

on:
  push:
    branches: [ "main" ]

jobs:

  createPR:

    runs-on: ubuntu-latest

    steps:
    -
      name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - 
      name: Create pull request
      run: gh pr create -B main -H prod --title 'Push "main" to "prod"' --body 'Created by Github action'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      
